### PR TITLE
Identify GCP Column Dinamically

### PR DESCRIPTION
**Pull request by GiovanniYuriMita**
## Description

This Pull Request aims to identify the pricing table and column dynamically instead of hardcoding `hystaxcom.pricing_dataset.cloud_pricing_export` and  `prices.list_price`. 

Besides that, following the Issue https://github.com/hystax/optscale/issues/445, I tried to add new machines types.

## Related issue number

[445](https://github.com/hystax/optscale/issues/445)

## Special notes

Please, notice that Firewall, Region and Network related changes can be ignored since my local version was built on version 2024091201-public.

## Checklist

* [ ] The pull request title is a good summary of the changes
* [ ] Unit tests for the changes exist
* [ ] New and existing unit tests pass locally

### CODE REVIEW

**Comment by sd-hystax** [comment]
Greetings, @GiovanniYuriMita!
There is no need to dynamically search for the 'list_price' field, because according
to the documentation it is always called that: https://cloud.google.com/billing/docs/how-to/export-data-bigquery-tables/pricing-data
Please check if you are using the wrong dataset (please note that billing_data and pricing_data are not the same thing)
There is also a possibility that the service account does not have access
to "bigquery.tables.get", therefore, it is better to always use the service_credentials config for such things.
P.S. Why did you remove the discover_firewalls function? It is used for insecure_security_groups recommendations

**Comment by GiovanniYuriMita** [comment]
Hey @sd-hystax,

Thank you so much for the update.

I’m afraid I didn’t fully understand the intended behavior here. I’ve adjusted the code to align with this specific dataset:
image

These changes were necessary as I was encountering the following errors:

```
WARNING:insider.insider_api.handlers.v2.base:403 POST /insider/v2/flavors (10.254.0.39):\n'Traceback (most recent call last):\n  File "/usr/src/app/tools/cloud_adapter/clouds/gcp.py", line 1089, in _query_prices\n    result = query_job.result()\n             ^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1520, in result\n    do_get_result()\n  File "/usr/local/lib/python3.12/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func\n    return retry_target(\n           ^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.12/site-packages/google/api_core/retry.py", line 191, in retry_target\n    return target()\n           ^^^^^^^^\n  File "/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1510, in do_get_result\n    super(QueryJob, self).result(retry=retry, timeout=timeout)\n  File "/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 922, in result\n    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result\n    raise self._exception\ngoogle.api_core.exceptions.Forbidden: 403 Access Denied: Table hystaxcom:pricing_dataset.cloud_pricing_export: User does not have permission to query table hystaxcom:pricing_dataset.cloud_pricing_export, or perhaps it does not exist.\n\nLocation: US\nJob ID: e56d7786-77ee-4f60-b0f4-2dc58db0bbdf\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/src/app/insider/insider_api/controllers/flavor.py", line 381, in find_gcp_flavor\n    self.gcp.get_instance_types_priced, region).result()\n                                                ^^^^^^^^\n  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result\n    raise self._exception\n  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/insider/insider_api/controllers/base.py", line 38, in cached_cloud_call\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/tools/cloud_adapter/clouds/gcp.py", line 1204, in get_instance_types_priced\n    machine_family_prices = self._get_machine_family_resource_prices(region)\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/tools/cloud_adapter/clouds/gcp.py", line 1131, in _get_machine_family_resource_prices\n    for row in self._query_prices(sku_desription_pattern):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/tools/cloud_adapter/clouds/gcp.py", line 1091, in _query_prices\n    raise ForbiddenException(str(ex))\ntools.cloud_adapter.exceptions.ForbiddenException: 403 Access Denied: Table hystaxcom:pricing_dataset.cloud_pricing_export: User does not have permission to query table hystaxcom:pricing_dataset.cloud_pricing_export, or perhaps it does not exist.\n\nLocation: US\nJob ID: e56d7786-77ee-4f60-b0f4-2dc58db0bbdf\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/src/app/insider/insider_api/handlers/v2/flavors.py", line 218, in post\n    res = await self.controller.find_flavor(**params)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/insider/insider_api/controllers/flavor.py", line 114, in find_flavor\n    return find_flavor_function_map[cloud_type][resource_type](**params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/insider/insider_api/controllers/flavor.py", line 387, in find_gcp_flavor\n    raise OptForbidden(Err.OI0020, [])\ntools.optscale_exceptions.common_exc.ForbiddenException: Forbidden\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute\n    result = await result\n             ^^^^^^^^^^^^\n  File "/usr/src/app/insider/insider_api/handlers/v2/flavors.py", line 226, in post\n    raise OptHTTPError.from_opt_exception(403, ex)\ntools.optscale_exceptions.http_exc.OptHTTPError: HTTP 403: Forbidden\n'
WARNING:tornado.access:403 POST /insider/v2/flavors (10.254.0.39) 2113.33ms
```

Despite my service account having these permissions:
image
image

I suspected the error might be due to a hardcoded reference to `hystaxcom:pricing_dataset.cloud_pricing_export`. After making the adjustments, the initial error was resolved, but I began seeing warnings indicating that certain machine types could not be priced:

```
INFO:insider.insider_api.handlers.v2.flavors:Received flavor search parameters: {'cloud_type': 'gcp_cnr', 'resource_type': 'instance', 'region': 'southamerica-east1', 'family_specs': {'source_flavor_id': 'e2-medium'}, 'mode': 'current', 'currency': 'BRL'}
INFO:tools.cloud_adapter.clouds.gcp:Identified pricing column: cost
WARNING:tools.cloud_adapter.clouds.gcp:failed to dicover price for c2-standard-16 in southamerica-east1
WARNING:tools.cloud_adapter.clouds.gcp:failed to dicover price for c2-standard-30 in southamerica-east1
WARNING:tools.cloud_adapter.clouds.gcp:failed to dicover price for c2-standard-4 in southamerica-east1
WARNING:tools.cloud_adapter.clouds.gcp:failed to dicover price for c2-standard-60 in southamerica-east1
...
```

Please note, this PR is not intended for merging. I opened it to facilitate troubleshooting for [issue #445](https://github.com/hystax/optscale/issues/445) as requested.

Regarding the firewall function, my repo was based on an older release (about two months old) that did not include it. Updating to the latest release still results in the same permissions exception in insider-api for `hystaxcom:pricing_dataset.cloud_pricing_export`.

Sorry for any confusion caused! I just need some help to get GCP recommendations.

**Comment by sd-hystax** [comment]
@GiovanniYuriMita 
You don't have the necessary dataset (i see only billing datasets). So you need to create it. This doc could help:
https://cloud.google.com/billing/docs/how-to/export-data-bigquery-setup
You need a **Pricing data** dataset

A little explanation:
For this recommendation, we are looking for SKUs that are suitable for your instance. Information on these SKUs may not be available in billing report because you are not using all possible instance types (only billed). But this information always present in pricing data

**Comment by sd-hystax** [comment]
A little explanation:
For this recommendation, we are looking for SKUs that are suitable for your instance. Information on these SKUs may not be available in billing report because you are not using all possible instance types. But this information always present in pricing data

**Comment by GiovanniYuriMita** [comment]
Hey @sd-hystax,

I have followed the GCP doc and updated the insider-api, insider-worker and insider-scheduler to the latest public version, but I still got the same error:

```
WARNING:insider.insider_api.handlers.v2.base:403 POST /insider/v2/flavors (10.254.0.39):\n'Traceback (most recent call last):\n  File "/usr/src/app/tools/cloud_adapter/clouds/gcp.py", line 1089, in _query_prices\n    result = query_job.result()\n             ^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1520, in result\n    do_get_result()\n  File "/usr/local/lib/python3.12/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func\n    return retry_target(\n           ^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.12/site-packages/google/api_core/retry.py", line 191, in retry_target\n    return target()\n           ^^^^^^^^\n  File "/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1510, in do_get_result\n    super(QueryJob, self).result(retry=retry, timeout=timeout)\n  File "/usr/local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 922, in result\n    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result\n    raise self._exception\ngoogle.api_core.exceptions.Forbidden: 403 Access Denied: Table hystaxcom:pricing_dataset.cloud_pricing_export: User does not have permission to query table hystaxcom:pricing_dataset.cloud_pricing_export, or perhaps it does not exist.\n\nLocation: US\nJob ID: 87c23a06-119f-4138-b698-2a9a6ac5efcb\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/src/app/insider/insider_api/controllers/flavor.py", line 381, in find_gcp_flavor\n    self.gcp.get_instance_types_priced, region).result()\n                                                ^^^^^^^^\n  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result\n    raise self._exception\n  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/insider/insider_api/controllers/base.py", line 38, in cached_cloud_call\n    result = fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/tools/cloud_adapter/clouds/gcp.py", line 1204, in get_instance_types_priced\n    machine_family_prices = self._get_machine_family_resource_prices(region)\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/tools/cloud_adapter/clouds/gcp.py", line 1131, in _get_machine_family_resource_prices\n    for row in self._query_prices(sku_desription_pattern):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/tools/cloud_adapter/clouds/gcp.py", line 1091, in _query_prices\n    raise ForbiddenException(str(ex))\ntools.cloud_adapter.exceptions.ForbiddenException: 403 Access Denied: Table hystaxcom:pricing_dataset.cloud_pricing_export: User does not have permission to query table hystaxcom:pricing_dataset.cloud_pricing_export, or perhaps it does not exist.\n\nLocation: US\nJob ID: 87c23a06-119f-4138-b698-2a9a6ac5efcb\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/src/app/insider/insider_api/handlers/v2/flavors.py", line 218, in post\n    res = await self.controller.find_flavor(**params)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/insider/insider_api/controllers/flavor.py", line 114, in find_flavor\n    return find_flavor_function_map[cloud_type][resource_type](**params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/src/app/insider/insider_api/controllers/flavor.py", line 387, in find_gcp_flavor\n    raise OptForbidden(Err.OI0020, [])\ntools.optscale_exceptions.common_exc.ForbiddenException: Forbidden\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute\n    result = await result\n             ^^^^^^^^^^^^\n  File "/usr/src/app/insider/insider_api/handlers/v2/flavors.py", line 226, in post\n    raise OptHTTPError.from_opt_exception(403, ex)\ntools.optscale_exceptions.http_exc.OptHTTPError: HTTP 403: Forbidden\n'
```

Is the setup supposed to "mock" the hystaxcom:pricing_dataset.cloud_pricing_export table?

Apologies if this seems basic—I’ve tried multiple approaches without success.

**Comment by sd-hystax** [comment]
Hey @GiovanniYuriMita 
Your fix for changing `hystaxcom:pricing_dataset.cloud_pricing_export` to `{self._pricing_table_full_name()}` is correct and you should keep it. Also you should keep extended maps with machine descriptions.
what you need to do is change the dataset name for your gcp service credentials (in overlay) to your **Pricing data** dataset

**Comment by GiovanniYuriMita** [comment]
Hey @sd-hystax,

Thank you soooooo much for all the help!

Indeed, there were 2 issues:

1. I needed to change `hystaxcom:pricing_dataset.cloud_pricing_export` to `{self._pricing_table_full_name()}`;
2. The GCP account only had billing dataset. After enabling the pricing one, the right list_price field appeared. I just changed it on the overlay and it worked like a charm.

Thank you, @sd-hystax and @stanfra for all the help. I'll close this merge now.

image

**Pull request closed without merging**
